In [1]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder

In [2]:
# Load in the pre-appointment-data
df = pd.read_csv('pre-appointment-data.csv')

# Mix the order of the data
df = df.sample(frac=1).reset_index(drop=True)

# Drop the columns that we don't need (symptom_cause, additional_symptoms, medical_history)
df = df.drop(['symptom_cause', 'additional_symptoms', 'medical_history'], axis=1)

# show the first 5 rows of the data
df.head()

,reason_for_visit,symptoms,duration,symptom_type,symptom_severity,appointment_expectations,health_concerns,health_experiences
0,Feeling overwhelmed and stressed,"Stress, anxiety, mood swings",2 months,Mental,Severe,To receive a diagnosis and start treatment,Worried about the impact on my relationships a...,Stressed and anxious
1,Cough and chest pain,"Cough, chest pain, fever",1 week,Respiratory,Moderate,To receive a diagnosis and treatment plan,Concerned about my lung health,Frustrated and overwhelmed
2,Chest pain and chronic cough,"Coughing, chest pain, can't get enough air, fe...",1 year,Respiratory,Severe,To receive a diagnosis and treatment plan,Worried about my heart and lung health,Feeling very sick and can't get enough air
3,I have been experiencing frequent stomach issues,"Nausea, vomiting, diarrhea",1 month,Digestive,Severe,To receive a diagnosis and treatment plan,Concerned about the cause of my symptoms,Scared and anxious
4,Experiencing sleep problems and mood swings,"Sleep problems, mood swings, irritability",3 weeks,Mental,Mild,To receive a diagnosis and treatment plan,Worried about the cause of my symptoms,Exhausted and emotional

In [3]:
# Encode the non-numeric columns
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = LabelEncoder().fit_transform(df[col])

In [4]:
# Drop the label to create the X data
X = df.drop('symptom_type', axis=1)
X.head()

,reason_for_visit,symptoms,duration,symptom_severity,appointment_expectations,health_concerns,health_experiences
0,63,104,4,2,24,51,53
1,23,21,1,1,25,9,35
2,12,34,2,2,25,39,25
3,84,88,0,2,25,12,49
4,38,100,9,0,25,46,10

In [5]:
# df symptom_type column
# Encode the labels
y = LabelEncoder().fit_transform(df['symptom_type'])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# Scale the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Show the first 5 rows of the scaled X_train data
print(X_train[:5])

[[ 0.27577031  0.88466474 -0.81765601  1.24191851 -0.0940496  -0.12577802
  -0.0188321 ]
 [-1.31309608 -0.76773796  0.30804715 -0.10958104 -0.34484852  0.91667018
   1.09602794]
 [ 0.27577031  0.91470842 -0.81765601  1.24191851 -0.0940496  -1.01930504
   1.09602794]
 [ 1.66602839  0.07348523 -1.0990818  -1.46108059 -0.84644636 -0.05131743
  -0.0188321 ]
 [-0.27040251  0.3438784   1.15232451 -1.46108059  3.16633637  0.46990667
  -2.56708361]]

In [6]:
df.to_csv('preprocessed-data.csv', index=False)